### ISSUE TITLE
prebuilt reference files and masked genome bed file with T2T-CHM13 genome

### ISSUE THREAD

**Issue by zou-yawen** [KiddLab/fastCN#2]
Hi, Sorry to bother you.When I use fastCN,I meet some problem.Could you please help me .I download a T2T-CHM13 genome from ucsc; How shoul I do to prebuilt reference files and masked genome bed file.

**Comment by jmkidd** [comment]
Yes, the recommendations for making a masked reference can be more explicit. We usually mask out RepeatMasker, TRF, and WindowMasker regions, plus 50-mers that are present 20 or more times.  This works for most genomes.  The control regions should exclude regions that are likely copy number variable, such as annotated segmental duplications as well regions of known CNV.  These can usually be lifted over from other assemblies if they are not available.  I'll add a readme with some more instructions.
